spring.application.name=backend

# --- Conexión a la base de datos PostgreSQL en Render ---
spring.datasource.url=jdbc:postgresql://dpg-d6it93paae7s739cltag-a.frankfurt-postgres.render.com/manually_db
spring.datasource.username=manually_db_user
# IMPORTANTE: He ocultado tu contraseña por seguridad. Pega aquí la que tenías.
spring.datasource.password=i83U5UxjLIirLrFpaUI99D1TG6BtJqct

# --- Configuración de JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Configuración del puerto y scripts ---
server.port=${PORT:8080}
spring.sql.init.mode=never